#!/bin/bash
cur_bri=$(/usr/bin/cat /sys/class/backlight/pwm-backlight.0/brightness)

if [ $1 == "up" ] ; then
    bri=$(($cur_bri+200))
    `echo $bri > /sys/class/backlight/pwm-backlight.0/brightness`
fi

if [ $1 == "down" ] ; then
    bri=$(($cur_bri-200))
    `echo $bri > /sys/class/backlight/pwm-backlight.0/brightness`
fi

if [ $1 == "-s" ]; then
    `echo $2 > /sys/class/backlight/pwm-backlight.0/brightness`
fi

